version: '3.8'

services:
  trickeddice-api:
    build: 
      context: ./TrickedDice.Api
      dockerfile: Dockerfile
    ports:
      - "5069:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # En producción, la cadena de conexión apuntaría al contenedor 'sql-server'
      # - ConnectionStrings__DefaultConnection="Server=sql-server;Database=db41007;User Id=sa;Password=SuperSecretPass123!;TrustServerCertificate=True;"
    depends_on:
      - sql-server
    restart: unless-stopped

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperSecretPass123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data: